name: React Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        working-directory: demo-web
        run: npm install

      - name: Run tests
        working-directory: demo-web
        run: npm test -- --watchAll=false

      - name: Build application
        working-directory: demo-web
        run: npm run build

